(() => {
  const METERS_PER_UNIT = window.NIGHT_HEIST_METERS_PER_UNIT || (1.42 / 3.6);
  const STORE_KEY='nightHeistProgressV2', MODE_KEY='nightHeistDriveMode';
  function readProgress(){try{const s=JSON.parse(localStorage.getItem(STORE_KEY)||'{}');return{fame:s.fame||0,totalLoot:s.totalLoot||0,best:s.best||{}}}catch{return{fame:0,totalLoot:0,best:{}}}}
  function saveProgress(){try{localStorage.setItem(STORE_KEY,JSON.stringify(progress))}catch{}}
  const progress=readProgress();window.NightHeistProgress=progress;
  const fameRank=f=>f>=45?'LEGGENDA':f>=28?'FANTASMA':f>=15?'RICERCATO':f>=7?'PILOTA':'RECLUTA';
  const money=v=>v>=1000000?`€${(v/1000000).toFixed(v%1000000?1:0)}M`:v>=1000?`€${Math.round(v/1000)}K`:`€${Math.round(v)}`;

  let driveMode;try{driveMode=localStorage.getItem(MODE_KEY)||'assist'}catch{driveMode='assist'}if(driveMode!=='manual')driveMode='assist';window.NightDriveMode=driveMode;
  const modeBox=document.createElement('div');modeBox.className='drive-mode-selector';modeBox.innerHTML='<span>GUIDA</span><button type="button" data-drive-mode="assist">ASSIST</button><button type="button" data-drive-mode="manual">FULL MANUAL</button><em id="careerMeta"></em>';
  const envGrid=document.getElementById('environmentGrid');envGrid?.parentNode?.insertBefore(modeBox,envGrid);const careerMeta=modeBox.querySelector('#careerMeta');
  function syncMode(){window.NightDriveMode=driveMode;ENVIRONMENTS.forEach(env=>{if(driveMode==='manual'){env.steerAssist=0;env.laneAssist=.0001;env.followAssist=-.835164835;env.cornerAssist=-1.642857143;env.manualShare=.55}else{env.steerAssist=3.20;env.laneAssist=1.72;env.followAssist=1.86;env.cornerAssist=1.62;env.manualShare=.20}});modeBox.querySelectorAll('[data-drive-mode]').forEach(b=>{const on=b.dataset.driveMode===driveMode;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on?'true':'false')});const footer=document.querySelector('.menu-footer span');if(footer)footer.textContent=driveMode==='assist'?'Guida: ASSIST':'Guida: FULL MANUAL'}
  function syncCareer(){if(careerMeta)careerMeta.textContent=`FAMA ${progress.fame} · ${fameRank(progress.fame)} · ${money(progress.totalLoot)}`}
  modeBox.addEventListener('click',e=>{const b=e.target.closest('[data-drive-mode]');if(!b)return;driveMode=b.dataset.driveMode;try{localStorage.setItem(MODE_KEY,driveMode)}catch{}syncMode();audio.uiClick()});syncMode();syncCareer();

  const hudCenter=document.querySelector('.hud-center'),escapeStatus=document.createElement('div');escapeStatus.className='escape-status';escapeStatus.innerHTML='<span id="escapeRemaining">FUGA · --</span><strong id="escapeSafety">CREA DISTANZA DALLA POLIZIA</strong>';hudCenter?.appendChild(escapeStatus);const remainingEl=escapeStatus.querySelector('#escapeRemaining'),safetyEl=escapeStatus.querySelector('#escapeSafety');
  const threatFrame=document.createElement('div');threatFrame.className='threat-vignette';document.body.appendChild(threatFrame);
  const preview=document.createElement('div');preview.className='route-preview hidden';preview.innerHTML='<span class="route-preview__title">BIVIO</span><div class="route-preview__choices"></div>';document.body.appendChild(preview);const previewChoices=preview.querySelector('.route-preview__choices');
  const resultPanel=document.getElementById('resultPanel'),extra=document.createElement('div');extra.className='result-extra';extra.innerHTML='<div><span>TEMPO</span><strong id="resultTime">--</strong></div><div><span>DERAPATE</span><strong id="resultDrifts">0</strong></div><div><span>BOTTINO</span><strong id="resultLoot">€0</strong></div><div><span>RANK</span><strong id="resultRank">★</strong></div><p id="resultRecord"></p>';resultPanel?.querySelector('.result-stats')?.after(extra);
  const resultTime=extra.querySelector('#resultTime'),resultDrifts=extra.querySelector('#resultDrifts'),resultLoot=extra.querySelector('#resultLoot'),resultRank=extra.querySelector('#resultRank'),resultRecord=extra.querySelector('#resultRecord');
  const fmtTime=sec=>{const m=Math.floor(sec/60),s=sec-m*60;return`${m}:${s.toFixed(1).padStart(4,'0')}`};

  function dirFromNode(path,nodeId){if(!path?.points?.length)return null;if(path.nodeA===nodeId){const a=path.points[0],b=path.points[Math.min(2,path.points.length-1)];return Math.atan2(b.y-a.y,b.x-a.x)}if(path.nodeB===nodeId){const n=path.points.length-1,a=path.points[n],b=path.points[Math.max(0,n-2)];return Math.atan2(b.y-a.y,b.x-a.x)}return null}
  function nextJunction(g){const info=g.road.nearestInfo(g.player.x,g.player.y);if(!info?.path?.nodeA||!g.road.nodeMap)return null;const tangent=Math.atan2(info.ty,info.tx),forward=Math.cos(angleWrap(tangent-g.player.angle))>=0,nodeId=forward?info.path.nodeB:info.path.nodeA,node=g.road.nodeMap.get(nodeId);return node?{info,node,nodeId,d:Math.hypot(g.player.x-node.x,g.player.y-node.y)}:null}
  function pathRisk(g,path,node,rel){const copMeters=Math.min(Infinity,...(g.cops||[]).map(c=>Math.hypot(c.x-node.x,c.y-node.y)*METERS_PER_UNIT));if(copMeters<230)return{icon:'◆',label:'POLIZIA',className:'danger'};if(path.trafficTrait==='slow')return{icon:'▥',label:'TRAFFICO LENTO',className:'warn'};if(path.trafficTrait==='tight'||path.feature==='switchback'||Math.abs(rel)>1.15)return{icon:'⌁',label:'CURVA CIECA',className:'warn'};if(path.kind==='highway'||path.feature==='elevated'||path.trafficTrait==='clear')return{icon:'↗',label:'STRADA LIBERA',className:'safe'};return{icon:'•',label:'NORMALE',className:'normal'}}
  function allowedPath(g,path){const level=g.player?._roadLevel||0;if(path.feature==='elevated-ramp')return level===0?path.rampDirection==='up':path.rampDirection==='down';return(path.level||0)===level}
  function updateRoutePreview(g){if(!g||state!=='playing'){preview.classList.add('hidden');return}const j=nextJunction(g),trigger=Math.max(310,Math.abs(g.player.speed)*1.65);if(!j||j.d>trigger||j.d<55||!(j.node.edges?.length>1)){preview.classList.add('hidden');return}const byId=new Map((g.road.paths||[]).map(p=>[p.id,p])),items=[];for(const id of j.node.edges){const path=byId.get(id);if(!path||path.id===j.info.path.id||path.kind==='service'||!allowedPath(g,path))continue;const a=dirFromNode(path,j.nodeId);if(a===null)continue;const rel=angleWrap(a-g.player.angle);if(Math.abs(rel)>2.45)continue;items.push({side:Math.abs(rel)<.36?'DRITTO':rel<0?'SINISTRA':'DESTRA',rel,risk:pathRisk(g,path,j.node,rel)})}if(!items.length){preview.classList.add('hidden');return}items.sort((a,b)=>a.rel-b.rel);previewChoices.innerHTML=items.slice(0,3).map(x=>`<div class="route-choice ${x.risk.className}"><b>${x.side}</b><span>${x.risk.icon} ${x.risk.label}</span></div>`).join('');preview.classList.remove('hidden')}

  function startAmbience(env){if(!audio.ctx||!audio.master)return;if(audio._immersion){for(const n of audio._immersion.nodes||[]){try{n.stop?.()}catch{}try{n.disconnect?.()}catch{}}}const ac=audio.ctx,nodes=[],out=ac.createGain();out.gain.value=.0001;out.connect(audio.master);nodes.push(out);const buffer=ac.createBuffer(1,ac.sampleRate*2,ac.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.65;const noise=ac.createBufferSource();noise.buffer=buffer;noise.loop=true;const filter=ac.createBiquadFilter(),gain=ac.createGain();if(env.propMode==='city'){filter.type='highpass';filter.frequency.value=1100;gain.gain.value=.018}else if(env.propMode==='industrial'){filter.type='bandpass';filter.frequency.value=180;gain.gain.value=.025}else if(env.propMode==='alpine'){filter.type='bandpass';filter.frequency.value=620;filter.Q.value=.55;gain.gain.value=.020}else{filter.type='lowpass';filter.frequency.value=520;gain.gain.value=.020}noise.connect(filter);filter.connect(gain);gain.connect(out);noise.start();nodes.push(noise,filter,gain);const pad=ac.createOscillator(),padGain=ac.createGain();pad.type=env.propMode==='industrial'?'sawtooth':'triangle';pad.frequency.value=env.propMode==='alpine'?48:env.propMode==='desert'?42:55;padGain.gain.value=0;pad.connect(padGain);padGain.connect(out);pad.start();nodes.push(pad,padGain);out.gain.setTargetAtTime(1,ac.currentTime,.6);audio._immersion={nodes,out,padGain,nextRadio:performance.now()+5000}}
  function stopAmbience(){const im=audio._immersion;if(!im||!audio.ctx)return;im.out?.gain?.setTargetAtTime(0,audio.ctx.currentTime,.18)}

  const PreviousGame=Game;Game=class ExperienceGame extends PreviousGame{
    constructor(env){super(env);this._runStartedAt=performance.now();this._drifts=0;this._nearBuzzAt=0;startAmbience(env)}
    updatePlayer(dt){if(window.NightDriveMode!=='manual')return super.updatePlayer(dt);const p=this.player,beforeAngle=p.angle;super.updatePlayer(dt);if(!p._drift?.active){const hand=keys.has('Space'),steerStrength=(1.30-clamp(Math.abs(p.speed)/245,0,.46))*(hand?1.36:1);p.angle=beforeAngle+p.steer*steerStrength*dt*(p.speed/100);p._assistSmoothAngle=p.angle;if(p._roadAssist){p._roadAssist.route=null;p._roadAssist.intent=null}}}
    update(dt){const d=this.player?._drift,wasActive=!!d?.active,wasHold=d?.hold||0;super.update(dt);if(wasActive&&!this.player?._drift?.active&&wasHold>.18){this._drifts++;navigator.vibrate?.([14,18,8])}this.updateExperienceFeedback()}
    updateExperienceFeedback(){if(!this.player)return;const minWorld=Math.min(Infinity,...(this.cops||[]).map(c=>dist2(c,this.player))),copMeters=minWorld*METERS_PER_UNIT,threat=Number.isFinite(copMeters)?clamp((220-copMeters)/145,0,1):0;window.NightHeistThreat=threat;threatFrame.style.opacity=(threat*.72).toFixed(3);threatFrame.classList.toggle('urgent',threat>.35);if(threat>.48&&performance.now()>this._nearBuzzAt){navigator.vibrate?.([18,45,18]);this._nearBuzzAt=performance.now()+1050}if(audio.ctx&&audio.siren){const now=audio.ctx.currentTime,wave=.5+.5*Math.sin(performance.now()*.0095);audio.siren.gain.gain.setTargetAtTime((threat>.01?.025:0)+threat*.105,now,.045);audio.siren.a.frequency.setTargetAtTime(610+wave*(210+threat*95),now,.025);audio.siren.b.frequency.setTargetAtTime(900-wave*(190+threat*80),now,.025)}const im=audio._immersion;if(im&&audio.ctx){im.padGain.gain.setTargetAtTime(.0025+this.heat*.008+threat*.012,audio.ctx.currentTime,.18);if((threat>.34||this.heat>.72)&&performance.now()>im.nextRadio){audio.burst(390+Math.random()*90,.035,'square');setTimeout(()=>audio.burst(280+Math.random()*70,.025,'square'),95);im.nextRadio=performance.now()+6500+Math.random()*8500}}const total=this.env.escapeKm*1000,remaining=Math.max(0,total-this.distance);if(remainingEl)remainingEl.textContent=`FUGA · ${(remaining/1000).toFixed(1)} km RIMANENTI`;if(safetyEl){if(remaining<1000&&copMeters>210)safetyEl.textContent='QUASI LIBERO · MANTIENI LA DISTANZA';else if(copMeters<180)safetyEl.textContent='PERICOLO · PATTUGLIA MOLTO VICINA';else if(copMeters<300)safetyEl.textContent='ALLONTANA LA POLIZIA';else safetyEl.textContent='CREA DISTANZA · CERCA LA VIA PIÙ RAPIDA'}if(ui.copDistance&&Number.isFinite(copMeters))ui.copDistance.textContent=`POLIZIA PIÙ VICINA: ${Math.max(0,Math.round(copMeters))} m`;updateRoutePreview(this)}
    end(win){if(this.finished)return;const elapsed=(performance.now()-this._runStartedAt)/1000,distance=this.distance,target=this.env.escapeKm*1000,runPct=clamp(distance/target,0,1),record=progress.best[this.env.id]||{},newDistance=!record.maxDistance||distance>record.maxDistance,newTime=win&&(!record.bestTime||elapsed<record.bestTime),earnedLoot=win?2400000:0,fameGain=win?(3+ENVIRONMENTS.indexOf(this.env)*2):Math.max(0,Math.floor(runPct*2));super.end(win);stopAmbience();record.maxDistance=Math.max(record.maxDistance||0,distance);if(win)record.bestTime=Math.min(record.bestTime||Infinity,elapsed);progress.best[this.env.id]=record;progress.totalLoot+=earnedLoot;progress.fame+=fameGain;saveProgress();syncCareer();const speedScore=clamp((this.maxSpeed-120)/90,0,1),stars=win?clamp(3+Math.round(speedScore)+Math.min(1,Math.floor(this._drifts/3)),3,5):clamp(1+Math.floor(runPct*2),1,3);if(resultTime)resultTime.textContent=fmtTime(elapsed);if(resultDrifts)resultDrifts.textContent=String(this._drifts);if(resultLoot)resultLoot.textContent=money(earnedLoot);if(resultRank)resultRank.textContent='★'.repeat(stars)+'☆'.repeat(5-stars);if(resultRecord){const isRecord=newTime||(!win&&newDistance);resultRecord.textContent=isRecord?`NUOVO RECORD PERSONALE · ${this.env.name}`:`FAMA +${fameGain} · ${fameRank(progress.fame)}`;resultRecord.classList.toggle('is-record',isRecord)}if(!win){const left=Math.max(0,target-distance);ui.resultCopy.textContent=`Sei stato catturato a ${(left/1000).toFixed(1)} km dalla meta. Riprova subito o cambia mappa.`;ui.retry.textContent='RIPROVA SUBITO'}else{ui.resultCopy.textContent=`Fuga completata in ${fmtTime(elapsed)}. Bottino al sicuro: ${money(earnedLoot)}.`;ui.retry.textContent='ALTRA FUGA'}preview.classList.add('hidden');threatFrame.style.opacity='0';window.NightHeistThreat=0}
  };
  ui.menuButton?.addEventListener('click',()=>{stopAmbience();preview.classList.add('hidden');threatFrame.style.opacity='0';window.NightHeistThreat=0});
  const baseShowMenu=showMenu;showMenu=function(){stopAmbience();preview.classList.add('hidden');threatFrame.style.opacity='0';window.NightHeistThreat=0;baseShowMenu()};
})();